#============== rabbit ===================
spring:
    rabbitmq:
        channelCacheSize: 50000
        concurrentConsumers: 100
        host: 127.0.0.1
        listener:
            direct:
                acknowledge-mode: manual
            simple:
                acknowledge-mode: manual
                retry:
                    enabled: false
        password: guest
        port: 5672
        username: guest
#============== kafka ===================
    kafka:
        bootstrap-servers: 192.168.0.106:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          group-id: test
          enable-auto-commit: true
          auto-commit-interval:
                            ms: 1000
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


